# INTRODUCTION {#ref-intro}

Stock assessment is a critical tool in supporting the sustainable management of fisheries. Although single species stock assessments provide the primary advisory product for many fisheries management decisions, they are often based solely on biological (e.g. survey) and fishery data. However, it has long been recognized that the underlying population dynamics of fish stocks are the result of complex interactions between fish productivity metrics (e.g. recruitment, natural mortality, growth), fishing activity, and environmental drivers [@hilbornQuantitativeFisheriesStock1992; @waltersResearchEnvironmentalFactors1988]. Although the effect of fishing is pivotal to, and accounted for, in most stock assessments, the effects of environmental factors are rarely considered. In a review of more than 1250 stocks world-wide, [@skern-mauritzenEcosystemProcessesAre2016] found that only 2% included environmental considerations, quantitatively or qualitatively. In US stock assessments ecosystem considerations were considered more frequently [25% [@marshallInclusionEcosystemInformation2019]. Whereas in Canada, 27% of stock assessments provided advice that included climate, oceanographic, or ecological considerations, and 21% included environmental variables quantitatively either in the population model or by using time-varying biological parameters thought to be related to environmental drivers [@pepinIncorporatingKnowledgeChanges2022].

For fisheries managers, the consideration of environmental conditions and their effect on fish stocks is increasingly required. This is largely in response to demands on fisheries management to mitigate, adapt, and respond to the impacts of climate change [@wilsonAdaptiveComanagementAchieve2018; @dfoFrameworkIncorporatingClimatechange2019] and stock assessment science is increasingly being asked to develop environment-inclusive assessments to inform more flexible and responsive fishery management strategies [@branderImpactsClimateChange2010; @nyeChangingSpatialDistribution2009; @linkEcosystembasedFisheriesManagement2011; @dfoFrameworkIncorporatingClimatechange2019]. For example, Canada’s newly revised Fisheries Act (R.S.C., 1985, c. F-14,) states that environmental conditions affecting a stock shall be taken into account when maintaining and rebuilding the stock [@dfoActAmendFisheries2019]. Typically, research into understanding the linkages between environmental variables and stock productivity metrics is a pre-requisite for environmental variables to be considered in the stock assessments process and subsequent science advice [@pepinIncorporatingKnowledgeChanges2022]. Then, when such relationships are found, integration and acceptance into the stock assessment process usually requires a relatively strong relationship and high degree of confidence in the mechanism [@edwardsProceedingsTechnicalExpertise2017; @pepinIncorporatingKnowledgeChanges2022]. If strong changes in a populations state are related to environmental variables, then it is often assumed that incorporating those environmental variables into the stock assessment process will improve the science advice and thus management outcomes will improve. However, best practices when incorporating environmental data into stock assessments should include an evaluation of quantifiable benefit[@edwardsProceedingsTechnicalExpertise2017]. 

For the world’s largest wild scallop fisheries, the sea scallop (*Placopecten magellanicus*) found off the northeastern United States and eastern Canada, reliable indices of recruitment are available through fishery independent surveys; however, outside of major recruitment events, annual variations in growth underlie major fluctuations in catch rate and yield. Growth is an integrated response of energy acquisition and expenditure. For scallop, growth can be defined either in terms of an increase in some dimension of the shell or in terms of the change in the soft tissue [@macdonaldPhysiologyEnergyAcquisition2016]. Shell growth continues as scallops age and generally the adductor muscle increases with shell size; however, the growth and size of the adductor muscle will also vary throughout the year (e.g. resorption of somatic tissue; @macdonaldInfluenceTemperatureFood1985a; @vahlEnergyTransformationsIceland1981]. For *P. magellanicus*, intra-annual changes in the meat weight for the same shell height are characterized by increases in weight in late winter and early spring and declines during spawning in the late summer and early fall [@naiduReproductionBreedingCycle1970; @robinsonSeasonalChangesSoftbody1981; @thompsonIdentifyingSpawningEvents2014] . This seasonal pattern is attributed to gametogenesis and the buildup of energy reserves; however, the magnitude of this cycle has been observed to vary between years within season [@robinsonSeasonalChangesSoftbody1981; @macdonaldInfluenceTemperatureFood1985a; @macdonaldInfluenceTemperatureFood1985; @macdonaldInfluenceTemperatureFood1986; @macdonaldInfluenceTemperatureFood1986; @schickAllometricRelationshipsGrowth1992].

In Canada, the scallop adductor muscle is the harvested part of the scallop, with landings reported and managed (e.g. catch limits) in terms of the biomass (weight) of the adductor meat (muscle). Sea scallops reach a harvestable size of about 100 mm shell height [average age of 4 to 5 years; @stewartEnvironmentalRequirementsSea1994]. From annual monitoring survey data, an allometric relationship between the weight of the adductor muscle and shell height is calculated and referred to as “scallop condition” (SC) [@hubleyGeorgesBankBrowns2014]. one year ahead for quota setting, and this projection requires an assumption of SC (DFO, 2018). Currently, the stock assessment model’s one-year projection to inform fisheries management decision making assumes SC is unchanged from the previous year. The environment-condition relationship identified in @liuUsingSatelliteRemote2021. Therefore, for the same catch level, more scallops will be harvested when SC is low than when SC is high.

Satellite remote sensing data has been found to predict the condition of Sea Scallop up to 18 months into the future on the Canadian portion of Georges Bank [@liuUsingSatelliteRemote2021]. SC was found to be highly correlated with Sea Surface Temperature (SST) in the winter of the previous year (January-March) and the winter of the current year (January-February).   The science advice for this scallop stock is based on projecting a population dynamics model [liuUsingSatelliteRemote2021]. The current assessment uses the SC from the previous year as the predicted SC for the model projections of future year's [@hubleyGeorgesBankBrowns2014; @dfoStockStatusUpdate2018]. This approach cannot account for environmental effects that may alter SC after the previous years survey estimate of SC is obtained. While this SC-SST model provides a novel means of predicting inter-annual changes in SC, it has yet to be compared to the current method used to predict SC nor has the quantitative impact of incorporating this predictive model into the tactical assessment framework been assessed. 

<!-- Alternatively, a methodology that incorporates environmental effects could result in improved predictions of SC and in turn lead to more accurate biomass projections and science advice.  -->

The purpose of this study was to quantify the potential impact of a SST-informed condition model within the existing stock assessment modelling framework, and to assess if this environmentally-informed approach improved one-year projections of fishable biomass for sea scallop on the Canadian portion of Georges Bank. We evaluate the SST-informed condition model developed by @liuUsingSatelliteRemote2021, as well as other SST-informed condition model formulations and discuss the results in the context of best practices related to incorporating environmental information into single-species stock assessment frameworks. 

<!-- There is an urgent need to sustainably manage fish stocks due to pressures from over-fishing, pollution, habitat destruction, and climate change [@faoStateWorldFisheries2018]. While it is well known that oceanographic conditions influence natural fluctuations in fish stocks, disentangling environmental variability from fishing effects remains challenging, often due to non-stationarity, non-linearity, and a lack of scientific resources to characterize the complex dynamics [@myersWhenEnvironmentRecruitment1998; @skern-mauritzenEcosystemProcessesAre2016]. For this reason stock assessment methods historically account for only the effects of population demographics and fishing while ignoring environmental effects outright [@skern-mauritzenEcosystemProcessesAre2016]. The integration of environmental data directly into traditional stock assessment models remains the exception [@cadrinStockAssessmentMethods2015].  -->

<!-- Part of the challenge is to overcome the difficulties associated with the short-term, *tactical* nature of the stock assessment process which typically requires predictions between 1-5 years in the future (they are the weather-people of Fisheries Science). Incorporation of environmental data within a tactical process requires the development of an environmental relationship that has a predictable impact on the assessment (e.g. CITE). In contrast, many fisheries scientists developing environmental relationships tend to focus on a long-term *strategic* perspective that attempts to understand the dynamics of populations, communities, and ecosystems at decadal or longer time frames (e.g. CITE). Identifying and utilizing environmental relationships from a strategic perspective has proven easier to achieve than from a tactical perspective (CITE).  In large part this is due to the differing objectives of the two perspectives, strategic objectives tend to be broader in nature (e.g. impacts of directed temperature change on ecosystem dynamics), whereas tactical objectives are more narrow, sensitive, and specific (e.g. setting a quota for a fishery using a biomass prediction for next year). While it is widely recognized that improved understanding of the influence of environmental variability on fish population dynamics could improve science advice within an ecosystem context and help operationalize an ecosystem approach to fisheries management (EAFM; CITE STUFF), this must be done with the tactical objectives in mind. -->

<!-- From a fisheries management perspective environmental considerations are increasingly required as part of the provision of tactical science advice. This is largely in response to demands on fisheries management to mitigate, adapt, and respond to the impacts of climate change [@wilsonAdaptiveComanagementAchieve2018; @dfoActAmendFisheries2019]. Fisheries management decisions often include setting removals limits in terms of biomass. However, these decisions are complicated by fluctuations in stock size due to variability in productivity parameters such as recruitment, growth, condition, and survival, all of which are influenced by the environment. -->

<!-- These environment-productivity relationships have been of interest to fisheries scientists throughout the history of the field [Other old stuff? @bevertonDynamicsExploitedFish1957;@rickerStockRecruitment1954]. The relationship between the environment and recruitment was one of the first, and is one of the more common, environmental relationships that has been explored [CITE]. However the development of long-term predictable relationships between recruitment and environmental conditions has been challenging and has limited the incorporation of these relationships into tactical assessment processes [@myersWhenEnvironmentRecruitment1998]. The influence of environmental factors on natural mortality has also been the focus of a great deal of research [CITE SOME STUFF]. The incorporation of these natural mortality-environmental relationships has been achieved by allowing natural mortality to vary over time within an assessment model [@swainExtremeIncreasesNatural2015]. In part, this method has been successfully incorporated into tactical decision making because the environmental driver was both well measured and the fluctuations from year to year were relatively predictable [@swainExtremeIncreasesNatural2015]. Additionally, the flexibility of the modelling framework allows the productivity parameter to track the known environmental change without an explicit link between the two [@swainExtremeIncreasesNatural2015]. -->

<!-- Finally, there is a long history of research exploring the relationship between environmental factors and individual growth and condition [@macdonaldInfluenceTemperatureFood1985a; @ratzVariationFishCondition2003a; @daufresneGlobalWarmingBenefits2009; @baudronWarmingTemperaturesSmaller2014; @ahtiSizeDoesMatter2020]. At a broad scale it has been suggested that fish tend to grow to larger sizes at high latitudes (Bergmanns rule; bergmannUeberVerhaltnissederWarmeokonomie1847; rayApplicationBergmannAllen1960], although there is also evidence that fishing and local environmental factors lead to these patterns breaking down [@fisherBreakingBergmannRule2010; @belkBergmannRuleEctotherms2002].  Some of the local environmental factors that influence individual growth within a stock include temperature [@neuheimerGrowingDegreedayFish2007], food availability [@niciezaGrowthCompensationJuvenile1997], and pH [@cattanoLivingHighCO22018]. Similarly, fish condition [average individual weight at a given size, e.g. Fulton's K, @nashOriginFultonCondition2006] has been related to numerous environmental variables including the timing of the onset and duration of the spring bloom [@reedResponseScotianShelf2019], temperature [@brossetInfluenceEnvironmentalVariability2015], and food limitations [@geissingerFoodInitialSize2021; @malzahnNutrientLimitationPrimary2007].  Despite these well known environmental effects, the impact of the environment on individual growth and condition is typically excluded from quantitative models developed for tactical decision making processes, likely due the lack of predictability of these relationships in future years. -->

<!-- On the Canadian portion of Georges Bank (GB) satellite remote sensing data has been found to predict the condition of Sea Scallop (*Placotpecten magellanicus*) up to 18 months into the future [@liuUsingSatelliteRemote2021]. Scallop condition (SC; the meat weight of a scallop with a shell height of 100 mm) was found to be highly correlated to the additive effect of Sea Surface Temperature (SST) in the winter of the previous year (January-March) and the winter of the current year (January-February). In the stock assessment of this scallop stock, the SC prediction for a given year is used to convert population abundance estimates to population biomass and is required to project the biomass of the stock into future years.  Thus, the environment-condition relationship identified in @liuUsingSatelliteRemote2021 can be *tactically* incorporated into the assessment for this stock [@hubleyGeorgesBankBrowns2014; @dfoStockStatusUpdate2018]. The current assessment uses the SC from the previous year as the predicted SC for the model projections of future year's [@hubleyGeorgesBankBrowns2014; @dfoStockStatusUpdate2018]. This approach cannot account for environmental effects that may alter SC after the previous years survey estimate of SC is obtained. While this SC-SST model provides a novel means of predicting inter-annual changes in SC, it has yet to be compared to the current method used to predict SC nor has the quantitative impact of incorporating this predictive model into the tactical assessment framework been assessed.  -->

<!-- <!-- Alternatively, a methodology that incorporates environmental effects could result in improved predictions of SC and in turn lead to more accurate biomass projections and science advice.  --> -->

<!-- The primary purpose of this study was to determine whether utilizing the predictive SC-SST model developed by @liuUsingSatelliteRemote2021 within the existing stock assessment modelling framework reduces the uncertainty of the tactical science advice for sea scallop on the Canadian portion of GB. Our objectives were to a) compare the predictive ability of the SC-SST models to the existing method used to predict SC for the stock assessment, b) quantify the difference between the biomass predictions and the realized biomass, and (c) discuss suggested best practices when undertaking research to incorporate environmental information into existing tactical science advice frameworks. -->

<!-- <!-- Many relationships between environmental conditions and some metric of productivity (recruitment, growth, natural mortality) have been identified (CITATIONS). Unfortunately, incorporation of these relationships into the science advice for fisheries management advice has often proven challenging. The relationships observed often change over time, or break down completely, making it challenging to use for science advice (CITATIONS). In other circumstances the environment-productivity relationship may not be relevant to the stock assessment framework itself, for example, identifying a relationship between larval survival and temperature, while ecologically of interest, will have little impact on the stock assessment if an index of juvenile recruitment is available and used in the provision of science advice.  Another challenge is the availability of the necessary data, science advice is often required on a regular schedule,  but if the environmental data necessary to inform the stock assessment isn't available until after the science advice is provided what's the point. --> -->


<!-- <!-- *NOW EXPAND THIS SECTION TO BE ABOUT FISH CONDITION...Expand on fish condition and how better knowledge of fish condition will lead to better estimates of biomass* --> -->
<!-- <!-- *Now talk about using environmental information to estimate condition. Point to papers using Oceanographic data (if they exist) and other useful environment-condition papers I find. End by pointing to our SRS paper* --> -->

<!-- <!-- Growth is an integrated response of energy acquisition and expenditure. For scallop, growth can be defined either in terms of an increase in some dimension of the shell or in terms of the change in the soft tissue [@macdonaldPhysiologyEnergyAcquisition2016]. Shell growth continues as scallops age and generally the adductor muscle increases with shell size; however, the growth and size of the adductor muscle will also vary throughout the year [e.g. resorption of somatic tissue: @vahlEnergyTransformationsIceland1981; @macdonaldInfluenceTemperatureFood1985]. For *P. magellanicus*, intra-annual changes in the meat weight for the same shell height are characterized by increases in weight in late winter and early spring and declines during spawning in the late summer and early fall [@naiduReproductionBreedingCycle1970; @robinsonSeasonalChangesSoftbody1981; @thompsonIdentifyingSpawningEvents2014]. This seasonal pattern is attributed to gametogenesis and the buildup of energy reserves; however, the magnitude of this cycle has been observed to vary between years within season [@robinsonSeasonalChangesSoftbody1981; @macdonaldInfluenceTemperatureFood1985; @macdonaldInfluenceTemperatureFood1985a; @macdonaldInfluenceTemperatureFood1986;@macdonaldInfluenceTemperatureFood1987; @schickAllometricRelationshipsGrowth1992a]. --> -->


<!-- <!-- Inter-annual differences in the weight of the adductor muscle (i.e. meat weight) for the same shell height are likely due to environmental conditions. When seasonal patterns are controlled for, spatial and depth differences in meat weight for a given shell size are often observed; with larger meats found at shallow water depths where temperature and food availability are often more favorable [@macdonaldInfluenceTemperatureFood1985; @macdonaldInfluenceTemperatureFood1986; @macdonaldInfluenceTemperatureFood1987; @schickAllometricRelationshipsGrowth1992a]. In sea scallops, food ration, consisting of suspended detrital material and phytoplankton, is a major factor in the regulation of growth and production [@cranfordParticleClearanceAbsorption1990; @shumwayFoodResourcesRelated1987; @macdonaldPhysiologyEnergyAcquisition2016]. Whereas temperature is positively correlated with metabolic rate, as measured by the rate of oxygen consumption [@shumwaySeasonalChangesOxygen1988; @macdonaldPhysiologyEnergyAcquisition2016]. There are also predictable seasonal changes in meat weight; for example, on Georges Bank the meat weight increases in the late winter and early spring, likely due to increased food availability, and declines in late summer and early fall due to the energetic demands of spawning [@thompsonIdentifyingSpawningEvents2014]. --> -->

<!-- <!-- The relationship between meat weight and shell height is usually defined using an allometric model [@laiLinearMixedeffectsModels2004; @hennenShellHeightToWeightRelationships2012; @sarroSpatialTemporalVariation2009] and in Canada’s Maritimes Region an allometric relationship is used to determine the meat weight of a 100 mm shell height scallop – hereafter referred to as Scallop Condition (SC). This index is used to track inter-annual change in meat condition and yearly fluctuations in SC have been observed to be as great as 30% [@hubleyGeorgesBankBrowns2014; @nasmithScallopProductionAreas2016; @sameotoScallopFishingArea2015].  --> -->