# RESULTS {#ref-results}

SC in May on GB ranged from `r min.cond` to `r max.cond` grams (Figure \@ref(fig:sc-sst-ts-plt)). The annual SC time series indicates that SC was generally below average in the 1980s and 1990s and has been above average since 2012 (Figure \@ref(fig:sc-sst-ts-plt)). The cumulative monthly SST in January-March was above average since 2012, except for 2019 (Figure  \@ref(fig:sc-sst-ts-plt)).

The relationship between SC and SST indicated that SST in the previous year ($SST_{t}$) was the primary driver of the relationship observed in @liuUsingSatelliteRemote2021, with the current year SST ($SST_{t+1}$) contributing little to the prediction (Table \@ref(tab:table-aic)). The previous year SST explained approximately `r previous.r2`% of the variability in SC, while the current year SST explained just `r cur.r2`% (Figure \@ref(fig:sc-sst-mod-plt)).  A 1°C increase in SST in the previous year resulted in a `r previous.effect` gram increase in SC, while a 1°C increase in SST in the current year resulted in an `r cur.effect` increase in SST. The lowest AIC found was for the model which included the interaction between the previous and current year SST (*SST interaction*), but the difference between this model and more parsimonious models was minimal (Table \@ref(tab:table-aic)). Thus the more parsimonious model (*SST Previous*), along with the *SST Full* model developed in @liuUsingSatelliteRemote2021, were retained for the retrospective analysis. 

The correlation analysis indicated that correlation in SC was highest when using only the previous year SC ($\rho$ = `r cor.tab$Correlation[1]`). The strength of the correlation declined as additional years were added, although the correlation using either the 2 or 5 year SC medians were also significantly different than 0 (Table \@ref(tab:table-cor) and Figure \@ref(fig:sc-cor-mod-plt)).  Given the strongest correlation was found using the previous year SC this model was retained for the retrospective analysis, this is referred to as the *Correlation method* hereafter.

## Retrospective Analysis

The retrospective analysis compared the biomass projections from two models using SST to predict current year SC, and one model that uses the previous year's SC to predict SC in the current year. The results of these three predictive models were compared to the realized biomass for the stock between 2000-2019 (Figure \@ref(fig:bm-ts-plt)). The biomass projections from these three models all tended to over predict the biomass in the following year. This overestimation was driven by the biomass projections in the period between 2009 and 2014 (Figure \@ref(fig:bm-ts-plt)). The difference between the projected biomass and the realized biomass was not significantly different for the three SC prediction methods, although the presently used *Correlation method* did have the least bias of the three methods tested (Figure \@ref(fig:bm-effect-plt)). Using the *Correlation method* the biomass projections were, on average, `r cor.bm.dif.est` tonnes above the realized biomass. The biomass projections for the two SST methods were effectively indistinguishable from each other; the biomass projection from the *SST Full* model was, on average, `r full.bm.dif.est` tonnes higher than realized (Figure \@ref(fig:bm-effect-plt)). In terms of percentages, the biomass projections tended to overestimate the biomass by more than 10%, with the *Correlation method* again having the least bias using this metric (`r cor.bm.prop.est`). The two SST methods were again indistinguishable from each other; the biomass projection from the *SST Full* model was `r full.bm.prop.est`% higher than realized (Figure \@ref(fig:bm-effect-plt)).

When the period between 2009 and 2014 were removed from the analysis, there was minimal bias in biomass projections for all three of the SC prediction methods (Figure \@ref(fig:bm-effect-drop09-14-plt)); the biomass projections were, on average, within 300 tonnes (within 2%) of the realized biomass in these years. In this subset of years there is no clearly preferred model; neither the bias nor precision of the biomass projections significantly differ between the three SC prediction methods.