<!-- So we reframe this discussion more around tactical and strategic aims.  This project does move us ahead strategically as we understand more about the patterns driving condition variability in scallop, but unfortunately in terms of quantitatively improving tactical advice this framework is not helpful.  So from the outset you should consider whether you need tactical or strategic advice, if strategic you are pretty much free to play in a sandbox, but you also shouldn't expect anything to 'be applied' with respect to tactical management of a stock.  If you are looking to use environmental relationship to inform tactical advice it is much more complicated and you need to think about the RIA principles from the outset of the project as if you don't meet those you aren't going to get anywhere. -->

# Discussion 

Scallop condition has varied by approximately `r CF.range` grams over the study period. The inter-annual variability in SC alone has been as large as `r CF.abs.vary` grams, and a maximum inter-annual percentage change in SC was `r CF.prop.vary`%. The incorporation of environmental data (SST) from the winter and spring period results in more accurate predictions of SC compared to the existing method. Despite this, the incorporation of this environmental relationship into the existing stock assessment framework does not improve the biomass projections for the upcoming year and thus does not quantitatively improve the tactical science advice. The results do, however, improve our understanding of the population dynamics of this stock, which can inform strategic fishery management approaches.  These results highlight the challenges of developing quantitative environmental relationships to provide tactically relevant environmentally-conditioned advice, and also reveal some principles that can guide the development of environmentally-conditioned tactical advice.

## The *RIA* principles (*Relevant*, *Impactful*, and *Available*) for Tactical Advice

At the outset of any project attempting to develop environmentally-conditioned science advice for tactical real time management,  everyone involved in the development of science advice should be consulted to determine whether the environmental relationship under study is ***relevant*** to the provision of tactical science advice [e.g. @bentleyRefiningFisheriesAdvice2021]. There are numerous methods by which environmental data could be incorporated into science advice, understanding how a particular environmental variable relates to the science advice will help to ensure the questions addressed by the research team are ***relevant*** for tactical decision making [@bentleyRefiningFisheriesAdvice2021]. 

There are numerous examples where relationships between environmental conditions and some metric of productivity (recruitment, growth, natural mortality) for a stock were identified but were not incorporated into the tactical decision making for that stock [CITE MORE; @myersWhenEnvironmentRecruitment1998]. In many cases these relationships were developed in isolation without consideration of the potential implementation within the assessment framework used for tactical decision making (CITATIONS). From a strategic perspective, there is certainly utility in understanding relationships between the environment and the dynamics of a stock, but if the end goal of a project is to use the results for tactical management of the stock, the research plans, questions, and objectives should align with this goal from the outset. For example, identifying a relationship between larval survival and temperature is of strategic interest, but if a reliable index of juvenile recruitment is already available and used in the provision of science advice then the relationship between larval survival and temperature is likely not ***relevant*** from a tactical perspective.  

Understanding the interaction between the assessment methodology and the environment-productivity relationship should be a priority during the early phase of the project. Underpinning a great deal of EAFM theory is the implicit assumption that quantitatively accounting for environmental variables within an assessment will improve tactical science advice (CITATIONS). Here we have shown that even with a strong relationship between an environmental variable and a productivity parameter, which is an integral component of an assessment model, this is not necessarily the case. If the goal of the project is to quantitatively improve the provision of tactical science advice, we recommend that simulation studies are undertaken to quantify the potential ***impact*** of the environmental variable (CITATIONS). In our case, a post-hoc simulation experiment was undertaken and indicated that a 1 gram change in SC resulted in a change in the model biomass predictions of approximately 1630 tonnes. Given the difference in the SC estimates between the methods explored was less than 0.2 grams on average there was little scope for improving the tactical science advice.  We recommend that simulation experiments like this are undertaken early in any project to quantify the impact on tactical advice as this will enable the research effort to focus on strategic goals or to be redirected to explore other environmental relationships that could directly improve the tactical science advice.

While the integration of environmental information into existing stock assessment frameworks can lead to achieving short-term EAFM goals, in the long-term, the development of Next-Generation stock assessment frameworks will likely have more dramatic impacts on integrating EAFM into tactical science advice [@puntEssentialFeaturesNextgeneration2020]. Examples of recent research themes to develop these frameworks include models that integrate  a) environmental considerations explicitly or implicitly into an assessment [@cadrinDefiningSpatialStructure2020; @puntEssentialFeaturesNextgeneration2020], b) ecosystem models with single species stock assessment to inform science advice [@bentleyRefiningFisheriesAdvice2021], and c) ecosystem and socio-economic factors directly into the science advisory process [e.g., @dornAssessmentWalleyePollock2020]. The development of Next-Generation assessment methods that can integrate ecosystem considerations directly into a stock assessment framework has received increased attention in recent years and promises a means of ensuring that  *relevant* environmental factors  ***impact***  the science advice [@dornAssessmentWalleyePollock2020; @mcdonaldExplicitIncorporationSpatial2021; @bentleyRefiningFisheriesAdvice2021]. tactical in-year science advice that is informed by environmental considerations should be a core goal during the development of any novel Next-Generation stock assessment framework. 

The final consideration in this process is to ensure the  ***availability*** of the necessary environmental data. tactical science advice is typically required on a regular pre-determined schedule, so the ***availability*** of the environmental data can also present a challenge. When ***relevant*** environmental relationships are identified that can ***impact*** tactical science advice but are not reliably ***available*** on the time-scale (or in the format) required then there is little utility in development of these relationships. For example, there were numerous other potential environmental indicators (e.g. oceanographic model indicators) that could have been used to predict SC for sea scallop on GB, but these data were not available 'in time' for the provision of the tactical science advice. One of these variables was oceanographic bottom temperature, this was found to be correlated with SC (unpublished), but because the data were not available in real time they could not be incorporated into the science advice process and this relationship was not explored further. Knowledge of the constraints on the timing of tactical science advice will enable proactive discussions regarding the utility of undertaking certain analyses and determine if data ***availability*** is a constraint. 

A related risk that should be considered during the genesis of a project is the reliability of the data pipeline itself. When the data informing an environmental relationships are not owned by the scientists developing the tactical science advice, there is a risk that external decisions could impact the *availability* of the data, and in turn the science advice. In these cases, the incorporation of the environmental relationship into the science advice would need to be resilient to the loss of these environmental data. Thus, establishing a means of ensuring long-term and reliable ***availability*** of the data should be undertaken.

# Conclusion

The integration of oceanographic and environmental data in stock assessment advice is critical to implementing an ecosystem approach to fisheries management (EAFM) and is required to inform climate-ready fisheries management strategies [@wilsonAdaptiveComanagementAchieve2018]. Projects attempting to utilize environmental information to better understand the dynamics of harvested stocks should identify their short-term tactical and long-term strategic objectives.  The results of this study show how the combination of environmental covariates with traditional fisheries survey data can improve our strategic understanding of the influence of the environment on an aspect of scallop productivity. Unfortunately, these results also highlight the challenges of integrating these relationships into existing stock assessment frameworks that provide tactical science advice. When attempting to incorporate ecosystem factors into tactical science advisory processes, it is necessary to ensure that the research, a) can address a component of productivity that is ***relevant*** to the tactical science advice, b) links to the factor(s) that ***impact*** the productivity of the system, and c) ensures the necessary data would be ***available*** when needed to provide tactical science advice. Developing environmental relationships that are *relevant*, *impactful*, and *available* (*RIA* principles) should underpin any efforts to develop tactical science advice in an EAFM context. Moreover, a number of emerging stock assessment frameworks are being developed that should improve our ability to create tactical environmentally informed science advice.

<!--  # STUFF TO ADD IN -->

<!-- The integration of stock assessment and EAFM research is needed to develop products and stock assessment models that can help move us towards EAFM/EBFM/EBM objectives, the time of the two solitudes must end. -->

<!-- There is often a disconnect between stock assessment research and EAFM research, if the integration of environmental information into science advice is to be successful, then the barriers between these two fields of research need to be eliminated so we no longer have the two solitudes. -->

<!-- Conventional sampling methods using research vessels are limited in space and time with fishery surveys and in-situ oceanographic sampling occurring at most a few times a year. In contrast, satellite remote sensing and oceanographic modelling outputs provides near continuous, high spatio-temporal environmental data; although, only remote sensed data products are available in near real time. While the overall best model incorporates both SST and MLD, this relationship cannot be operationalized because of the limitations on the *availability* of the MLD data. However, the *SST* model also improves the *prediction* of SC over the current biological-only methodology and these data are *available* in near real time. The *SST* model meets both the *predictive* and the *availability criteria* and this relationship can be operationalized within the stock assessment process to help improve science advice. -->


<!-- This is due to the relatively small bias in the biomass predictions from the model due to an over-estimate of other productivity parameters and a slight under-prediction of condition using the current method.  -->

<!-- There is a laundry list of environmental variables that correlate in some way to metrics of productivity for numerous stocks.  It has long been recognized that these relationship often break down over time and the use of environmental data in stock assessments has remained limited.  Unfortunately, we show how even when the relationship holds, it does not necessarily lead to better science advice.  And it’s not like condition doesn’t matter, it can lead to swings in biomass of up to 30% year over year.    -->

<!-- An additionally challenge that has received less attention is the practical challenge of implementation of these data into traditional stock assessments. Given the availability of the SST data in near real time, this should facilitate it’s use in the stock assessment process.  But, in this case, the SST in Jan-March is required to predict condition for the current year so even with this near real time availability of this data its use for tactical science advice for the current year is challenging and this relationship would serve no benefit if the science advice is required before this data is available.  The situation is more problematic for modelled oceanographic data which is not available in near real time and would rarely be available in time to inform science advice.    -->

<!-- These challenges suggest that in the near term the most useful path forward for utilizing environmental data may be to use it for strategic longer-term planning, for example to predict impacts of climate change (although extrapolating relationships to unobserved ecosystems states has its own suite of challenges).  In the longer-term, to achieve EAFM/EBFM/EBM goals it will require new stock assessment modelling frameworks in which the environmental considerations are intrinsically linked into the assessment (Punt).  A first step in this direction is Raph’s spatial paper in which spatial variability it accounted for in the assessment.  While this doesn’t account for environmental effects in the traditional sense, the spatial variability modelled through this method is integrating productivity changes due to environmental variability.  This and other next-gen stock assessment methods will likely need to be developed before we are able to have tactical in-year science advice that is fully informed by environmental and ecosystem considerations (Punt paper).  -->

<!-- The implications of this change on stock assessment advice is significant since SC is assumed as a known input and is currently assumed unchanged from the previous year for biomass projections, from which fisheries management decisions on removal levels are made [@hubleyGeorgesBankBrowns2014;@dfoStockStatusUpdate2018]. Model projections based on underestimates of SC will therefore inherently underestimate biomass and may result in economic loss, whereas overestimates of SC will overestimate biomass leading to an increased risk of over-exploitation, all else being equal.   -->

<!-- Through correlation analysis, cumulative SST was identified as most correlated with SC at the time of the survey in August. The periods of strongest correlation with SST were observed during January to April of the previous year and January to March of the current year. The observation that summer SC is correlated with this winter-spring period is supported by the annual cyclical nature of energy storage and utilization of  *P. magellanicus* [@naiduReproductionBreedingCycle1970; @sarroSpatialTemporalVariation2009; @thompsonIdentifyingSpawningEvents2014]. However, unexpectedly, SC did not show strong correlation with CHL or MLD, although further empirical modelling indicated that MLD did significantly improve the SC estimates (*Base* model).

 Although sea scallops exhibit an annual cyclical nature to their energy cycle, the results of the SST correlation analysis, *Base*, *SST*, and *AR(1)* models all support the notion that scallop condition is dependent on the cumulative environmental conditions experienced in the winter and spring period leading up to spawning and that this effect is not fully lost during spawning. Therefore, the condition of the scallop meat in August appears dependent on the environmental conditions up to 20 months prior. 

We found no evidence for a relationship between CHL and SC which was surprising given the role of phytoplankton in scallop diets  [@shumwayFoodResourcesRelated1987; @macdonaldPhysiologyEnergyAcquisition2016]. Clearance rates in *P. magellanicus* are positively correlated to temperature [@macdonaldFeedingActivityScallops2009], however they have been shown to be independent across a broad range of food concentrations  [@cranfordParticleClearanceAbsorption1990; @macdonaldVariationFoodQuality1994; @cranfordSituFeedingAbsorption1998] and may decline at high food concentrations [@grantSedimentResuspensionRates1997].  Our results, combined with the strong mixing and high primary productivity that characterizes Georges Bank [@townsendNitrogenLimitationSecondary1997; @townsendOceanographyNorthwestAtlantic2006], suggests that food availability may not limit growth and thus scallop condition on Georges Bank. Alternatively, phytoplankton blooms are generally of short duration and do not cover the entire domain used in this study; the lack of evidence for an effect of CHL may therefore be due to the aggregation of the data in both space (6,500 km^2^) and time (monthly average) used in this study [@songPhenologyPhytoplanktonBlooms2010] (**CJ and ED can you provide a reference here and what do we mean by short duration, size of typical bloom etc??**). Further research at a finer spatio-temporal scale that more closely matches the scale of the phytoplankton blooms may better resolve this relationship.

***Catherine/Emmanuel – a oceanographic paragraph to link SST, MLD, CHL and below observations:*** The increase in SC with increasing MLD (Base model) indicates that increased connectivity (mixing) between the surface and benthic communities generally leads to elevated condition SST direction with SC link to oceanography paragraph by CJ and ED.  link to oceanography paragraph by CJ and ED

**Is this a reasonable summary of Brickman, especially the effect about Temp anomalies being relatively uniform from surface to depth, ideas for other references?**
Within the SST range observed over the last two decades, SC improved when the SST in the spring was elevated and this effect was amplified when SST was elevated for consecutive years. The temperatures in the region have increased over the last decade, this has been driven by an increase in the occurrence of high salinity warm water eddies forming at the tail of the Grand Banks  [@brickmanMechanismRecentOcean2018]. These anomalous eddies propagate across the Scotian Shelf to the Gulf of Maine and are caused by an interaction between the Labrador Current and the Gulf Stream. Similar cold water eddies were likely more common in previous decades and appear to help regulate temperatures within the region during colder periods [@brickmanMechanismRecentOcean2018].  Within both cold and warm eddies the MLD would likely be above average and temperature anomalies are observed from near the surface to depths in excess of 120 meters. The SST anomaly would be correlated to the bottom temperature anomaly at the depths scallop inhabit on Georges Bank within an eddy which indicates that SST could be a good proxy for the environment scallop experience.  These eddies have a central role in modulating temperatures on Georges Bank and throughout the region, and therefore on the environmental conditions scallop experience.

Scallop meat weight declines rapidly in the fall and this decline is associated with the primary spawning event which generally begins in August and ends in October or November on Georges Bank [@posgayObservationSpawningSea1958; @naiduReproductionBreedingCycle1970; @thompsonIdentifyingSpawningEvents2014].  After spawning, scallop meat weight remains low until the winter, at which time the meat weight begins to increase and generally reaches a maximum by June; meat weight then remains similar until spawning and the cycle begins again [@macdonaldInfluenceTemperatureFood1985; @macdonaldInfluenceTemperatureFood1985a; @sarroSpatialTemporalVariation2009; @thompsonIdentifyingSpawningEvents2014]. The increase in scallop meat weight is a gradual process, taking up to half a year [@sarroSpatialTemporalVariation2009]; therefore, identifying the environmental attributes that most influence scallop productivity requires continuous environmental data such that the effect of integrated environmental conditions can be evaluated.
-->

