\clearpage

# TABLES {#ref-tabs}


\clearpage
<!-- Insert table 1 note how I'm dealing with the table caption here-->
```{r table-aic, echo=F,warning=F}

cap <- "AIC Table for SC-SST models"

options(knitr.kable.NA = '')
# NEED TO SORT THE meta call out in the index using bookdown instead of csasdown to mimic the behaviour to make table work automaticlaly in word an d pdf.

if(knitr_figs_dir == "knitr-figs-pdf/")
{
kableExtra::kbl(sst.aic.tab, booktabs = TRUE, escape =F, format='latex', caption = cap)
  
}

if(knitr_figs_dir != "knitr-figs-pdf/")
{
kableExtra::kbl(sst.aic.tab, booktabs = TRUE, escape =F, format = 'pipe', caption = cap)
}
```

```{r table-cor, echo=F,warning=F}

cap <- "Correlation between Current SC and SC at a 1-year lag, and the median of SC of the previous 2, 5, and 10 years."

options(knitr.kable.NA = '')
# NEED TO SORT THE meta call out in the index using bookdown instead of csasdown to mimic the behaviour to make table work automaticlaly in word an d pdf.

if(knitr_figs_dir == "knitr-figs-pdf/")
{
kableExtra::kbl(cor.tab, booktabs = TRUE, escape =F, format='latex', caption = cap)
  
}

if(knitr_figs_dir != "knitr-figs-pdf/")
{
kableExtra::kbl(cor.tab, booktabs = TRUE, escape =F, format = 'pipe', caption = cap)
}
```


\newpage
